YEAR: 'foreground_2015'
TRAIN_SENSOR: 'CrossMatch'
TEST_SENSOR: 'CrossMatch'
DATASET_PATH: '/home/hmb1604/datasets/LivDet'
BINARY_CLASS: false
BATCH_SIZE: 8
NUM_WORKERS: 4
BACKBONE_NAME: 'mobilenetv2'
LR: 0.01
WEIGHT_DECAY: 0.0001
NUM_EPOCHS: 1
SPOOF_WEIGHT: 1.0
MATERIAL_WEIGHT: 4.0
THRESHOLD: 0.5
MODEL_SAVE_PATH: './ckpts/model.pth'
SPOOF_CRITERION_TYPE: 'bce_with_logits'
MATERIAL_CRITERION_TYPE: 'cross_entropy'
SCHEDULER_TYPE: 'cosine_annealing'
OPTIMIZER_WEIGHT_DECAY: 0.0001
TRANSFORM_TYPE: 'basic'
VALID_SPLIT: 0.1
OPTIMIZER_TYPE: 'adam'